import type { Dispatch, SetStateAction } from "react";
import type { StyleProp, TextStyle } from "react-native";

import type { AppThemeColors } from "../../theme";
import type { HelpRequestInput } from "../../data/helpRequests";
import type { useTaskQueue } from "./useTaskQueue";
import type { Mechanism, Member, PartDefinition, PartInstance, Project, QaReport, ResponsibleGroup, Subsystem, Task, Workstream, WorkType } from "../../types/domain";
import type { ScheduleEntry } from "../../app/appModel";
import type { MilestoneSortField, Option, SummaryChipData, ResponsibleGroupFilter, TaskWorkspaceView } from "../../ui/types";

import type { ResponsiveScreenStyles } from "../types";

type StateSetter<T> = Dispatch<SetStateAction<T>>;
type TextSetter = StateSetter<string>;

export interface TaskScreenProps {
  queue: ReturnType<typeof useTaskQueue>;
  activeResponsibleGroupId: ResponsibleGroupFilter;
  events: ScheduleEntry[];
  isLandscapeTimelineLayout: boolean;
  openCreateDeadlineEditor: () => void;
  openCreateTaskEditor: () => void;
  openEditTaskEditor: (task: Task) => void;
  setActiveResponsibleGroupId: StateSetter<ResponsibleGroupFilter>;
  subsystems: Subsystem[];
  workspaceView: TaskWorkspaceView;
  tasks: Task[];
  themeColors: AppThemeColors;
  timelineTasks: Task[];
  activeResponsibleGroupLabel: string;
  responsibleGroups: ResponsibleGroup[];
  workstreamsById: Record<string, Workstream>;
  projects: Project[];
  appResponsiveStyles: ResponsiveScreenStyles;
  canReassignTasks: boolean;
  canSubmitQa: boolean;
  qaRequests: import("../../types/domain").QaRequest[];
  openCreateQaReportEditor: (taskId?: string, qaRequestId?: string) => void;
  claimTask: (task: Task) => Promise<void>;
  workTypesById: Record<string, WorkType>;
  editTagStyle: StyleProp<TextStyle>;
  eventsById: Record<string, ScheduleEntry>;
  isCompactLayout: boolean;
  isLandscapeCardLayout: boolean;
  mechanismsById: Record<string, Mechanism>;
  members: Member[];
  membersById: Record<string, Member>;
  openCreateWorkLogEditor: (taskId?: string) => void;
  partInstancesById: Record<string, PartInstance>;
  partDefinitionsById: Record<string, PartDefinition>;
  requestHelp: (input: HelpRequestInput) => boolean;
  requestTaskQa: (task: Task) => Promise<void>;
  reassignTask: (task: Task, ownerId: string | null) => Promise<void>;
  releaseTask: (task: Task) => Promise<void>;
  rosterMentors: Member[];
  rosterStudents: Member[];
  signedInMember: Member | null;
  startTask: (task: Task) => Promise<void>;
  subsystemsById: Record<string, Subsystem>;
  taskById: Record<string, Task>;
  taskDependencies: import("../../types/domain").TaskDependency[];
  taskLoggedHoursById: Record<string, number>;
  qaReports: QaReport[];
  eventOptions: Option[];
  setTimelineMilestoneFilter: TextSetter;
  setTimelineSubsystemFilter: TextSetter;
  timelineMilestoneFilter: string;
  timelineSubsystemFilter: string;
  filteredMilestones: ScheduleEntry[];
  milestoneSearch: string;
  milestoneSortField: MilestoneSortField;
  milestoneSortOrder: "asc" | "desc";
  milestoneSummary: SummaryChipData[];
  milestoneTypeFilter: string;
  openCreateMilestoneEditor: () => void;
  openEditMilestoneEditor: (event: ScheduleEntry) => void;
  setMilestoneSearch: TextSetter;
  setMilestoneSortField: StateSetter<MilestoneSortField>;
  setMilestoneSortOrder: StateSetter<"asc" | "desc">;
  setMilestoneTypeFilter: TextSetter;
}
