import type { Dispatch, SetStateAction } from "react";
import type { StyleProp, TextStyle } from "react-native";

import type { AppThemeColors } from "../../theme";
import type { HelpRequestInput } from "../../data/helpRequests";
import type { TaskQueueSection } from "../../data/taskQueueOrdering";
import type { Discipline, Event, Mechanism, Member, PartInstance, QaReview, Subsystem, Task } from "../../types/domain";
import type { ArchiveFilterMode, BlockerFilterMode, MilestoneSortField, Option, SummaryChipData, TaskSubteamTab, TaskViewTab, ViewTab } from "../../ui/types";

import type { ResponsiveScreenStyles } from "../types";

type StateSetter<T> = Dispatch<SetStateAction<T>>;
type TextSetter = StateSetter<string>;

export interface TaskScreenProps {
  activeTaskSubteam: TaskSubteamTab;
  events: Event[];
  isLandscapeTimelineLayout: boolean;
  openCreateDeadlineEditor: () => void;
  openCreateTaskEditor: () => void;
  openEditTaskEditor: (task: Task) => void;
  setActiveTaskSubteam: StateSetter<TaskSubteamTab>;
  subsystems: Subsystem[];
  taskView: TaskViewTab;
  themeColors: AppThemeColors;
  timelineTasks: Task[];
  activeTaskSubteamLabel: string;
  appResponsiveStyles: ResponsiveScreenStyles;
  canReassignTasks: boolean;
  claimTask: (task: Task) => Promise<void>;
  clearTaskBlockers: (task: Task, resolutionNote: string) => Promise<void>;
  disciplinesById: Record<string, Discipline>;
  editTagStyle: StyleProp<TextStyle>;
  eventsById: Record<string, Event>;
  filteredTaskQueue: Task[];
  isCompactLayout: boolean;
  isLandscapeCardLayout: boolean;
  mechanismsById: Record<string, Mechanism>;
  members: Member[];
  membersById: Record<string, Member>;
  openCreateWorkLogEditor: (taskId?: string) => void;
  partInstancesById: Record<string, PartInstance>;
  requestHelp: (input: HelpRequestInput) => boolean;
  requestTaskQa: (task: Task) => Promise<void>;
  reassignTask: (task: Task, ownerId: string | null) => Promise<void>;
  releaseTask: (task: Task) => Promise<void>;
  rosterMentors: Member[];
  rosterStudents: Member[];
  setTaskArchiveFilter: StateSetter<ArchiveFilterMode>;
  setTaskBlockerFilter: StateSetter<BlockerFilterMode>;
  setTaskOwnerFilter: TextSetter;
  setTaskPriorityFilter: TextSetter;
  setTaskSearch: TextSetter;
  setTaskStatusFilter: TextSetter;
  setTaskSubsystemFilter: TextSetter;
  setActiveTab: StateSetter<ViewTab>;
  signedInMember: Member | null;
  startTask: (task: Task) => Promise<void>;
  subsystemsById: Record<string, Subsystem>;
  taskArchiveFilter: ArchiveFilterMode;
  taskBlockerFilter: BlockerFilterMode;
  taskById: Record<string, Task>;
  taskOwnerFilter: string;
  taskPriorityFilter: string;
  taskQueueSections: TaskQueueSection[];
  taskSearch: string;
  taskStatusFilter: string;
  taskSubsystemFilter: string;
  taskLoggedHoursById: Record<string, number>;
  taskSummary: SummaryChipData[];
  qaReviews: QaReview[];
  eventOptions: Option[];
  setTimelineMilestoneFilter: TextSetter;
  setTimelineSubsystemFilter: TextSetter;
  timelineMilestoneFilter: string;
  timelineSubsystemFilter: string;
  filteredMilestones: Event[];
  milestoneSearch: string;
  milestoneSortField: MilestoneSortField;
  milestoneSortOrder: "asc" | "desc";
  milestoneSummary: SummaryChipData[];
  milestoneTypeFilter: string;
  openCreateMilestoneEditor: () => void;
  openEditMilestoneEditor: (event: Event) => void;
  setMilestoneSearch: TextSetter;
  setMilestoneSortField: StateSetter<MilestoneSortField>;
  setMilestoneSortOrder: StateSetter<"asc" | "desc">;
  setMilestoneTypeFilter: TextSetter;
}
