import type { Dispatch, SetStateAction } from "react";
import type { StyleProp, TextStyle } from "react-native";

import type { AppThemeColors } from "../../theme";
import type { HelpRequestInput } from "../../data/helpRequests";
import type { useTaskQueue } from "./useTaskQueue";
import type { Discipline, Event, Mechanism, Member, PartInstance, QaReview, Subsystem, Task } from "../../types/domain";
import type { MilestoneSortField, Option, SummaryChipData, TaskSubteamTab, TaskViewTab } from "../../ui/types";

import type { ResponsiveScreenStyles } from "../types";

type StateSetter<T> = Dispatch<SetStateAction<T>>;
type TextSetter = StateSetter<string>;

export interface TaskScreenProps {
  queue: ReturnType<typeof useTaskQueue>;
  activeTaskSubteam: TaskSubteamTab;
  events: Event[];
  isLandscapeTimelineLayout: boolean;
  openCreateDeadlineEditor: () => void;
  openCreateTaskEditor: () => void;
  openEditTaskEditor: (task: Task) => void;
  setActiveTaskSubteam: StateSetter<TaskSubteamTab>;
  subsystems: Subsystem[];
  taskView: TaskViewTab;
  themeColors: AppThemeColors;
  timelineTasks: Task[];
  activeTaskSubteamLabel: string;
  appResponsiveStyles: ResponsiveScreenStyles;
  canReassignTasks: boolean;
  canSubmitQa: boolean;
  qaRequests: import("../../types/domain").QaRequest[];
  openCreateQaReportEditor: (taskId?: string, qaRequestId?: string) => void;
  claimTask: (task: Task) => Promise<void>;
  clearTaskBlockers: (task: Task, resolutionNote: string) => Promise<void>;
  disciplinesById: Record<string, Discipline>;
  editTagStyle: StyleProp<TextStyle>;
  eventsById: Record<string, Event>;
  isCompactLayout: boolean;
  isLandscapeCardLayout: boolean;
  mechanismsById: Record<string, Mechanism>;
  members: Member[];
  membersById: Record<string, Member>;
  openCreateWorkLogEditor: (taskId?: string) => void;
  partInstancesById: Record<string, PartInstance>;
  requestHelp: (input: HelpRequestInput) => boolean;
  requestTaskQa: (task: Task) => Promise<void>;
  reassignTask: (task: Task, ownerId: string | null) => Promise<void>;
  releaseTask: (task: Task) => Promise<void>;
  rosterMentors: Member[];
  rosterStudents: Member[];
  signedInMember: Member | null;
  startTask: (task: Task) => Promise<void>;
  subsystemsById: Record<string, Subsystem>;
  taskById: Record<string, Task>;
  taskDependencies: import("../../types/domain").TaskDependency[];
  taskLoggedHoursById: Record<string, number>;
  qaReviews: QaReview[];
  eventOptions: Option[];
  setTimelineMilestoneFilter: TextSetter;
  setTimelineSubsystemFilter: TextSetter;
  timelineMilestoneFilter: string;
  timelineSubsystemFilter: string;
  filteredMilestones: Event[];
  milestoneSearch: string;
  milestoneSortField: MilestoneSortField;
  milestoneSortOrder: "asc" | "desc";
  milestoneSummary: SummaryChipData[];
  milestoneTypeFilter: string;
  openCreateMilestoneEditor: () => void;
  openEditMilestoneEditor: (event: Event) => void;
  setMilestoneSearch: TextSetter;
  setMilestoneSortField: StateSetter<MilestoneSortField>;
  setMilestoneSortOrder: StateSetter<"asc" | "desc">;
  setMilestoneTypeFilter: TextSetter;
}
