import { StyleSheet } from "react-native";

import { colors, spacing } from "../../theme";
import { planner } from "./landscapeTimelinePalette";

export const landscapeTimelineHeaderStyles = StyleSheet.create({
  header: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    zIndex: 20,
    elevation: 20,
  },
  title: {
    fontSize: 27,
    fontWeight: "900",
  },
  controls: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    zIndex: 21,
    elevation: 21,
  },
  viewSwitch: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    padding: 3,
  },
  viewSwitchButton: {
    minHeight: 30,
    minWidth: 86,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
  },
  viewSwitchLabel: {
    fontSize: 13,
    fontWeight: "900",
  },
  controlButton: {
    minHeight: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: planner.controlBorder,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
  },
  controlButtonActive: {
    borderColor: planner.today,
    backgroundColor: planner.controlActiveSurface,
  },
  controlLabel: {
    color: planner.controlMuted,
    fontSize: 15,
    fontWeight: "800",
  },
  controlLabelActive: {
    color: planner.controlActiveInk,
  },
  addButton: {
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: planner.addButton,
    paddingHorizontal: spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  addLabel: {
    color: colors.white,
    fontSize: 17,
    fontWeight: "900",
  },
  monthMenuAnchor: {
    position: "relative",
    zIndex: 30,
    elevation: 30,
  },
  monthMenu: {
    position: "absolute",
    top: 44,
    right: 0,
    width: 190,
    borderRadius: 8,
    borderWidth: 1,
    padding: spacing.xs,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    zIndex: 31,
    elevation: 31,
  },
  monthMenuYearRow: {
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  monthMenuYearButton: {
    minHeight: 30,
    minWidth: 54,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    borderWidth: 1,
  },
  monthMenuYearButtonText: {
    fontSize: 12,
    fontWeight: "900",
  },
  monthMenuYearLabel: {
    flex: 1,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "900",
  },
  monthMenuGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  monthMenuItem: {
    width: "33.33%",
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
  },
  monthMenuItemText: {
    fontSize: 13,
    fontWeight: "800",
  },
  addMenuAnchor: {
    position: "relative",
    zIndex: 5,
  },
  addMenu: {
    position: "absolute",
    top: 48,
    right: 0,
    width: 152,
    borderRadius: 8,
    borderWidth: 1,
    paddingVertical: spacing.xs,
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  addMenuItem: {
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  addMenuItemText: {
    fontSize: 14,
    fontWeight: "800",
  },
});
