import { StyleSheet } from "react-native";

import { colors, radii, shadows, spacing } from "../theme";
export const statusToneStyles = StyleSheet.create({
  success: {
    backgroundColor: "#dcfce7",
  },
  info: {
    backgroundColor: "#e0f2fe",
  },
  warning: {
    backgroundColor: "#fef3c7",
  },
  danger: {
    backgroundColor: "#fee2e2",
  },
  neutral: {
    backgroundColor: "#f1f5f9",
  },
});

export const statusToneLabelStyles = StyleSheet.create({
  success: {
    color: "#246847",
  },
  info: {
    color: "#075985",
  },
  warning: {
    color: "#92400e",
  },
  danger: {
    color: "#991b1b",
  },
  neutral: {
    color: "#475569",
  },
});

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  screenContent: {
    paddingBottom: spacing.xl,
  },
  topbar: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm,
    ...shadows.card,
  },
  topbarCompact: {
    marginHorizontal: spacing.md,
  },
  topbarLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  topbarRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    flexShrink: 0,
  },
  topbarRightCompact: {
    gap: spacing.xs,
  },
  iconButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    minHeight: 40,
    minWidth: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonLabel: {
    fontWeight: "800",
    color: colors.navyInk,
    fontSize: 12,
    letterSpacing: 0.5,
  },
  menuIcon: {
    width: 18,
    gap: 4,
  },
  menuIconBar: {
    height: 2,
    width: "100%",
    borderRadius: 999,
    backgroundColor: colors.navyInk,
  },
  shellIconLabel: {
    color: colors.navyInk,
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 16,
  },
  brandWrap: {
    flex: 1,
    minWidth: 0,
  },
  brandEyebrow: {
    color: colors.subtleText,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  brandTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 2,
  },
  brandTitleCompact: {
    fontSize: 16,
  },
  topbarSubtabDots: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  topbarSubtabDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.border,
  },
  userChip: {
    borderRadius: 999,
    backgroundColor: colors.navySurface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  userChipLabel: {
    color: colors.navyInk,
    fontWeight: "700",
    fontSize: 12,
    flexShrink: 1,
  },
  personButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.blue,
    backgroundColor: colors.navySurface,
    paddingHorizontal: spacing.sm,
    minHeight: 40,
    minWidth: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  personButtonLabel: {
    color: colors.navyInk,
    fontSize: 12,
    fontWeight: "900",
  },
  sidebarNavRow: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    gap: spacing.sm,
  },
  sidebarNavRowCompact: {
    paddingHorizontal: spacing.md,
  },
  sidebarTab: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  sidebarTabActive: {
    borderColor: colors.blue,
    backgroundColor: colors.navySurface,
  },
  sidebarIconBubble: {
    width: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: colors.canvas,
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarIconBubbleActive: {
    backgroundColor: colors.blue,
  },
  sidebarIconLabel: {
    color: colors.navyInk,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  sidebarIconLabelActive: {
    color: colors.white,
  },
  sidebarTabLabel: {
    color: colors.ink,
    fontWeight: "700",
    fontSize: 13,
  },
  sidebarTabLabelActive: {
    color: colors.navyInk,
  },
  sidebarCountPill: {
    minWidth: 26,
    height: 26,
    borderRadius: 999,
    backgroundColor: colors.canvas,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  sidebarCountPillActive: {
    backgroundColor: colors.blue,
  },
  sidebarCountLabel: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "800",
  },
  sidebarCountLabelActive: {
    color: colors.white,
  },
  sectionTabsRow: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    gap: spacing.sm,
  },
  sectionTab: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    backgroundColor: colors.surface,
  },
  sectionTabActive: {
    backgroundColor: colors.navySurface,
    borderColor: colors.blue,
  },
  sectionTabLabel: {
    color: colors.subtleText,
    fontWeight: "700",
    fontSize: 13,
  },
  sectionTabLabelActive: {
    color: colors.navyInk,
  },
  panel: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
    ...shadows.card,
  },
  panelCompact: {
    marginHorizontal: spacing.md,
  },
  panelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  panelHeaderCompact: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: spacing.sm,
  },
  panelHeaderCompactInline: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  panelHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  panelActions: {
    alignItems: "flex-end",
  },
  panelActionsCompact: {
    alignItems: "stretch",
  },
  panelTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "800",
  },
  panelSubtitle: {
    color: colors.subtleText,
    marginTop: 4,
    lineHeight: 18,
    fontSize: 13,
  },
  panelContent: {
    marginTop: spacing.sm,
    gap: spacing.sm,
  },
  primaryAction: {
    borderRadius: 999,
    backgroundColor: colors.blue,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryActionLabel: {
    color: colors.white,
    fontWeight: "800",
    fontSize: 13,
  },
  taskQueueHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: spacing.sm,
  },
  taskQueueFilterSheet: {
    width: "100%",
    maxHeight: "82%",
    borderRadius: radii.lg,
    borderWidth: 1,
    padding: spacing.md,
    ...shadows.card,
  },
  taskQueueFilterSheetContent: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  taskQueueFilterGroup: {
    gap: spacing.xs,
  },
  filterToolbar: {
    gap: spacing.sm,
  },
  searchFieldWrap: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.md,
    height: 42,
    justifyContent: "center",
  },
  searchFieldInput: {
    color: colors.ink,
    fontSize: 14,
    minWidth: 0,
  },
  optionChipRow: {
    gap: spacing.xs,
  },
  optionChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  optionChipActive: {
    backgroundColor: colors.navySurface,
    borderColor: colors.blue,
  },
  optionChipLabel: {
    color: colors.subtleText,
    fontSize: 12,
    fontWeight: "700",
  },
  optionChipLabelActive: {
    color: colors.navyInk,
  },
  dropdownButton: {
    minHeight: 42,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  dropdownButtonLabel: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  dropdownChevron: {
    color: colors.subtleText,
    fontSize: 12,
    fontWeight: "900",
  },
  dropdownScrim: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.36)",
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.lg,
  },
  dropdownMenu: {
    width: "100%",
    maxHeight: 240,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.xs,
    marginTop: spacing.xs,
    ...shadows.card,
  },
  dropdownMenuTitle: {
    color: colors.subtleText,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    fontWeight: "800",
    paddingHorizontal: spacing.xs,
    paddingBottom: spacing.xs,
  },
  dropdownOption: {
    borderRadius: 10,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  dropdownOptionLabel: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "700",
  },
  summaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  summaryChip: {
    minWidth: 104,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    flex: 1,
  },
  summaryChipLabel: {
    color: colors.subtleText,
    textTransform: "uppercase",
    fontSize: 10,
    letterSpacing: 0.8,
    fontWeight: "700",
  },
  summaryChipValue: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 4,
  },
  tableHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 6,
    marginTop: 2,
  },
  tableHeaderText: {
    color: colors.subtleText,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "700",
    flex: 1,
  },
  tableHeaderPrimary: {
    flex: 2,
  },
  tableHeaderButton: {
    flex: 1,
    alignItems: "flex-start",
  },
  tableHeaderButtonPrimary: {
    flex: 2,
    alignItems: "flex-start",
  },
  queueRowCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.sm,
    gap: 6,
  },
  queueRowCardLandscape: {
    padding: spacing.md,
    gap: spacing.sm,
  },
  taskCardLandscapeContent: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  taskCardLandscapeMain: {
    flex: 1.6,
    minWidth: 0,
    gap: spacing.xs,
  },
  taskCardLandscapeAside: {
    flex: 1,
    minWidth: 220,
    gap: spacing.xs,
  },
  queueRowHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  queueRowPrimaryText: {
    flex: 1,
    minWidth: 0,
  },
  queueRowTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  queueRowSubtitle: {
    color: colors.subtleText,
    fontSize: 13,
    marginTop: 3,
    lineHeight: 18,
  },
  queueRowBody: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 20,
  },
  queueMetaLine: {
    color: colors.subtleText,
    fontSize: 13,
    lineHeight: 18,
  },
  editTag: {
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    fontSize: 11,
    color: colors.subtleText,
    fontWeight: "700",
    letterSpacing: 0.5,
    flexShrink: 0,
  },
  editTagButton: {
    borderRadius: 999,
  },
  queuePillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: 4,
  },
  quickActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: 4,
  },
  quickActionButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  quickActionButtonPrimary: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  quickActionButtonLabel: {
    color: colors.navyInk,
    fontSize: 12,
    fontWeight: "800",
  },
  quickActionButtonPrimaryLabel: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  workTimerCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.md,
    gap: spacing.xs,
  },
  statusPill: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  statusPillLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  calloutBox: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
    marginTop: 4,
  },
  calloutTitle: {
    color: colors.orangeInk,
    fontWeight: "800",
    marginBottom: 4,
  },
  calloutBody: {
    color: colors.ink,
    lineHeight: 19,
  },
  homeSection: {
    gap: spacing.sm,
  },
  homeSectionHeader: {
    gap: 2,
  },
  inventoryAlertRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  attendanceRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    flexWrap: "wrap",
  },
  attendanceStatusControls: {
    flexDirection: "row",
    gap: spacing.xs,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  attendanceStatusButton: {
    minHeight: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  attendanceStatusButtonActive: {
    borderColor: colors.blue,
    backgroundColor: colors.navySurface,
  },
  attendanceStatusButtonLabel: {
    color: colors.subtleText,
    fontSize: 12,
    fontWeight: "800",
  },
  attendanceStatusButtonLabelActive: {
    color: colors.navyInk,
  },
  attendanceMark: {
    width: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  attendanceMarkLabel: {
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 21,
  },
  compactMetaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  compactMetaItem: {
    borderRadius: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.xs,
    paddingVertical: 4,
  },
  compactMetaText: {
    color: colors.subtleText,
    fontSize: 12,
    fontWeight: "700",
  },
  advancedOptions: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  advancedOptionsHeader: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  advancedOptionsTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  advancedOptionsToggle: {
    color: colors.navyInk,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  advancedOptionsBody: {
    gap: spacing.sm,
  },
  reportGrid: {
    gap: spacing.sm,
  },
  riskSeverityHigh: {
    borderColor: colors.orange,
    backgroundColor: colors.orangeSurface,
  },
  riskSeverityMedium: {
    borderColor: "rgba(233, 131, 53, 0.45)",
    backgroundColor: "rgba(233, 131, 53, 0.12)",
  },
  riskSeverityLow: {
    borderColor: "rgba(22, 71, 142, 0.26)",
    backgroundColor: "rgba(22, 71, 142, 0.08)",
  },
  riskLandscapeBoard: {
    width: "100%",
    flexDirection: "row",
    gap: spacing.md,
    paddingBottom: spacing.xs,
  },
  riskLandscapeColumn: {
    flex: 1,
    minWidth: 0,
    borderRadius: radii.lg,
    borderWidth: 1,
    padding: spacing.sm,
    gap: spacing.sm,
    ...shadows.card,
  },
  riskLandscapeColumnHeader: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  riskPriorityBadge: {
    minHeight: 32,
    borderRadius: 8,
    paddingHorizontal: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  riskPriorityBadgeHigh: {
    backgroundColor: "#fee2e2",
  },
  riskPriorityBadgeMedium: {
    backgroundColor: "#fef3c7",
  },
  riskPriorityBadgeLow: {
    backgroundColor: "#eef2f7",
  },
  riskPriorityBadgeText: {
    fontSize: 13,
    fontWeight: "900",
  },
  riskPriorityBadgeTextHigh: {
    color: "#991b1b",
  },
  riskPriorityBadgeTextMedium: {
    color: "#92400e",
  },
  riskPriorityBadgeTextLow: {
    color: "#475569",
  },
  riskColumnCount: {
    minWidth: 36,
    height: 36,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  riskColumnCountText: {
    fontSize: 16,
    fontWeight: "900",
  },
  riskLandscapeItem: {
    minHeight: 144,
  },
  interactionNote: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.navySurface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
  },
  interactionNoteExpanded: {
    gap: 4,
  },
  interactionNoteHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  interactionNoteLabel: {
    color: colors.navyInk,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    fontSize: 10,
    fontWeight: "800",
  },
  interactionNoteText: {
    color: colors.subtleText,
    lineHeight: 18,
    fontSize: 13,
  },
  interactionNoteToggle: {
    color: colors.navyInk,
    fontSize: 12,
    fontWeight: "800",
  },
  tutorialBody: {
    gap: spacing.sm,
  },
  tutorialControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  tutorialButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
    minWidth: 64,
    alignItems: "center",
  },
  tutorialButtonPrimary: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  tutorialButtonLabel: {
    color: colors.navyInk,
    fontSize: 12,
    fontWeight: "800",
  },
  tutorialButtonPrimaryLabel: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  tutorialDots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    flex: 1,
  },
  tutorialDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
  },
  emptyStateWrap: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    backgroundColor: colors.canvas,
  },
  emptyStateText: {
    color: colors.subtleText,
    lineHeight: 18,
  },
  timelineRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.md,
    gap: spacing.sm,
  },
  timelineRowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  timelineRowText: {
    flex: 1,
  },
  timelineTitle: {
    color: colors.ink,
    fontWeight: "800",
    fontSize: 15,
  },
  timelineMeta: {
    color: colors.subtleText,
    fontSize: 13,
    marginTop: 2,
  },
  timelineTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: colors.track,
    overflow: "hidden",
  },
  timelineFill: {
    height: "100%",
    backgroundColor: colors.blue,
  },
  subsectionLabel: {
    color: colors.ink,
    fontWeight: "800",
    fontSize: 16,
    marginTop: 2,
  },
  subsystemCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.md,
    gap: 7,
  },
  subsystemCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  subsystemExpansion: {
    marginTop: spacing.xs,
    gap: spacing.xs,
  },
  mechanismCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
  },
  rosterSection: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.md,
    gap: spacing.xs,
  },
  rosterSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  rosterSectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  rosterAddButton: {
    width: 36,
    height: 36,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  rosterAddButtonLabel: {
    color: colors.navyInk,
    fontSize: 22,
    fontWeight: "300",
    lineHeight: 24,
  },
  memberRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  memberRowSelected: {
    borderColor: colors.blue,
    backgroundColor: colors.navySurface,
  },
  memberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 999,
    backgroundColor: colors.navySurface,
    alignItems: "center",
    justifyContent: "center",
  },
  memberAvatarLabel: {
    color: colors.navyInk,
    fontSize: 13,
    fontWeight: "800",
  },
  memberAvatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
  },
  memberCopy: {
    flex: 1,
  },
  memberName: {
    color: colors.ink,
    fontWeight: "800",
  },
  memberRole: {
    color: colors.subtleText,
    marginTop: 2,
    fontSize: 12,
  },
  memberRoleBadge: {
    width: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.navySurface,
    alignItems: "center",
    justifyContent: "center",
  },
  memberRoleBadgeLabel: {
    color: colors.navyInk,
    fontSize: 11,
    fontWeight: "900",
  },
  modalScrim: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.lg,
  },
  modalScrimCompact: {
    padding: spacing.md,
  },
  modalCard: {
    width: "100%",
    maxWidth: 560,
    maxHeight: "88%",
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    ...shadows.card,
  },
  modalCardLandscape: {
    maxWidth: 920,
    maxHeight: "84%",
  },
  modalCardCompact: {
    maxHeight: "92%",
    padding: spacing.sm,
  },
  modalTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: "800",
  },
  modalContent: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
  },
  taskEditorStack: {
    gap: spacing.sm,
  },
  taskEditorLandscapeGrid: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  taskEditorLandscapeColumn: {
    flex: 1,
    minWidth: 0,
    gap: spacing.sm,
  },
  modalField: {
    gap: 6,
  },
  modalFieldLabel: {
    color: colors.subtleText,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.7,
    fontWeight: "700",
  },
  modalFieldInput: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    color: colors.ink,
    minHeight: 42,
  },
  modalFieldInputMultiline: {
    minHeight: 92,
  },
  profilePhotoField: {
    gap: spacing.sm,
  },
  profilePhotoPicker: {
    minHeight: 48,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  profilePhotoChooseButton: {
    borderRadius: 4,
    backgroundColor: "#6b7280",
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  profilePhotoChooseButtonLabel: {
    color: colors.white,
    fontSize: 13,
    fontWeight: "700",
  },
  profilePhotoFileName: {
    color: colors.ink,
    flex: 1,
  },
  profilePhotoClearButton: {
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  profilePhotoClearButtonLabel: {
    color: colors.ink,
    fontWeight: "800",
  },
  plannedDaysField: {
    gap: spacing.sm,
  },
  plannedDaysRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  plannedDayOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  plannedDayCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
  },
  plannedDayLabel: {
    color: colors.ink,
    fontWeight: "700",
  },
  toggleField: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  toggleFieldActive: {
    borderColor: colors.blue,
    backgroundColor: colors.navySurface,
  },
  toggleFieldLabel: {
    color: colors.ink,
    fontWeight: "700",
  },
  toggleFieldValue: {
    color: colors.subtleText,
    fontWeight: "700",
  },
  toggleFieldValueActive: {
    color: colors.navyInk,
  },
  modalActions: {
    marginTop: spacing.sm,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.sm,
    alignItems: "center",
    flexWrap: "wrap",
  },
  modalActionsCompact: {
    gap: spacing.xs,
  },
  modalActionButtonCompact: {
    width: "100%",
    minHeight: 40,
    marginRight: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  modalDeleteButton: {
    borderRadius: 999,
    backgroundColor: colors.orangeSurface,
    borderWidth: 1,
    borderColor: colors.orange,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    marginRight: "auto",
  },
  modalDeleteButtonLabel: {
    color: colors.orangeInk,
    fontWeight: "800",
  },
  modalCancelButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
  },
  modalCancelButtonLabel: {
    color: colors.subtleText,
    fontWeight: "700",
  },
  modalSaveButton: {
    borderRadius: 999,
    backgroundColor: colors.blue,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
  },
  modalSaveButtonLabel: {
    color: colors.white,
    fontWeight: "800",
  },
  workLogAddMenu: {
    width: "100%",
    maxWidth: 360,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.sm,
    ...shadows.card,
  },
  overlayScrim: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.34)",
    justifyContent: "flex-start",
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xxl,
  },
  navSwipeEdge: {
    position: "absolute",
    left: 0,
    top: 72,
    bottom: 0,
    width: 28,
    zIndex: 20,
  },
  navDrawerSafeArea: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.34)",
  },
  navDrawerScrim: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
  },
  navDrawer: {
    height: "100%",
    maxWidth: 336,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.md,
    ...shadows.card,
  },
  navDrawerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  navDrawerHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  navDrawerTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  navDrawerSubtitle: {
    color: colors.subtleText,
    fontSize: 13,
    marginTop: 2,
  },
  navDrawerCloseButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    minHeight: 40,
    minWidth: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  navDrawerCloseLabel: {
    color: colors.navyInk,
    fontSize: 14,
    fontWeight: "900",
  },
  navDrawerList: {
    gap: spacing.sm,
  },
  navDrawerSection: {
    gap: spacing.xs,
  },
  navDrawerSectionLabel: {
    color: colors.subtleText,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  navDrawerItem: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  navDrawerItemActive: {
    borderColor: colors.blue,
    backgroundColor: colors.navySurface,
  },
  navDrawerItemLabel: {
    color: colors.ink,
    flex: 1,
    fontSize: 14,
    fontWeight: "800",
  },
  overlayCard: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.sm,
    ...shadows.card,
  },
  overlayHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  overlayHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  overlayHeaderAction: {
    minHeight: 36,
    paddingHorizontal: spacing.xs,
    alignItems: "center",
    justifyContent: "center",
  },
  overlayHeaderActionLabel: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "500",
  },
  overlayTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  overlaySubtitle: {
    color: colors.subtleText,
    fontSize: 13,
    marginTop: 2,
  },
  overlayBody: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 20,
  },
  projectMark: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: colors.navySurface,
    alignItems: "center",
    justifyContent: "center",
  },
  projectMarkLabel: {
    color: colors.navyInk,
    fontSize: 13,
    fontWeight: "900",
  },
  personMark: {
    width: 42,
    height: 42,
    borderRadius: 999,
    backgroundColor: colors.navySurface,
    alignItems: "center",
    justifyContent: "center",
  },
  personMarkLabel: {
    color: colors.navyInk,
    fontSize: 13,
    fontWeight: "900",
  },
  overlayActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  overlayActionButton: {
    borderRadius: 999,
    backgroundColor: colors.blue,
    paddingHorizontal: spacing.md,
    paddingVertical: 9,
  },
  overlayActionLabel: {
    color: colors.white,
    fontWeight: "800",
  },
  overlaySecondaryButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    paddingHorizontal: spacing.md,
    paddingVertical: 9,
  },
  overlaySecondaryLabel: {
    color: colors.navyInk,
    fontWeight: "800",
  },
  loginScreen: {
    flex: 1,
  },
  loginScreenLight: {
    backgroundColor: colors.grey,
  },
  loginScreenDark: {
    backgroundColor: "#10284d",
  },
  loginSafeArea: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loginCard: {
    minHeight: 722,
    borderRadius: 29,
    alignItems: "center",
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 28,
  },
  loginCardLight: {
    backgroundColor: colors.grey,
  },
  loginCardDark: {
    backgroundColor: "#10284d",
  },
  loginBadgeShadow: {
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 13 },
    elevation: 8,
  },
  loginLogoImage: {
    width: 304,
    height: 334,
  },
  loginBadge: {
    width: 250,
    height: 250,
    borderRadius: 36,
    backgroundColor: "#1e5aae",
    padding: 12,
    transform: [{ rotate: "30deg" }],
  },
  loginBadgeInner: {
    flex: 1,
    borderRadius: 28,
    borderWidth: 4,
    borderColor: colors.red,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-30deg" }],
  },
  loginRocket: {
    height: 88,
    width: 40,
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: -6,
  },
  loginRocketBody: {
    width: 14,
    height: 58,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    backgroundColor: colors.red,
  },
  loginRocketFinLeft: {
    position: "absolute",
    top: 40,
    left: 6,
    width: 12,
    height: 34,
    borderTopLeftRadius: 12,
    backgroundColor: colors.red,
    transform: [{ rotate: "18deg" }],
  },
  loginRocketFinRight: {
    position: "absolute",
    top: 40,
    right: 6,
    width: 12,
    height: 34,
    borderTopRightRadius: 12,
    backgroundColor: colors.red,
    transform: [{ rotate: "-18deg" }],
  },
  loginRocketFlame: {
    position: "absolute",
    top: 62,
    width: 34,
    height: 52,
    borderLeftWidth: 17,
    borderRightWidth: 17,
    borderBottomWidth: 52,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: colors.grey,
  },
  loginArc: {
    width: 210,
    height: 52,
    borderTopWidth: 4,
    borderTopColor: colors.red,
    borderRadius: 110,
    marginTop: -6,
  },
  loginTeamText: {
    color: colors.red,
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 10,
    marginRight: -10,
    marginTop: -34,
  },
  loginMecoText: {
    color: colors.blue,
    fontSize: 50,
    fontWeight: "900",
    letterSpacing: 0,
    lineHeight: 58,
  },
  loginDivider: {
    width: 94,
    height: 3,
    backgroundColor: colors.red,
    marginTop: 2,
  },
  loginNumberText: {
    color: colors.red,
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 8,
    marginRight: -8,
    marginTop: 6,
  },
  loginTitle: {
    color: colors.white,
    fontSize: 28,
    fontWeight: "400",
    letterSpacing: 0,
    marginTop: 14,
    marginBottom: 16,
    textShadowColor: "rgba(0, 0, 0, 0.7)",
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 1,
  },
  loginFieldStack: {
    width: "100%",
    gap: 10,
  },
  loginEmailRow: {
    width: "100%",
    minHeight: 50,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 18,
    paddingRight: 8,
  },
  loginEmailRowLight: {
    backgroundColor: colors.blue,
    shadowColor: "#000000",
    shadowOpacity: 0.23,
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  loginEmailRowDark: {
    backgroundColor: "#172746",
  },
  loginCodeRow: {
    width: "100%",
    minHeight: 50,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 18,
    paddingRight: 8,
  },
  loginEmailInput: {
    flex: 1,
    minWidth: 0,
    color: colors.white,
    fontSize: 13,
    paddingVertical: 12,
  },
  loginSendButton: {
    width: "100%",
    minHeight: 44,
    borderRadius: 999,
    backgroundColor: colors.red,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    paddingHorizontal: 16,
  },
  loginInlineSendButton: {
    width: "auto",
    flexShrink: 0,
    marginLeft: 8,
    marginTop: 0,
  },
  loginSendButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "700",
  },
  loginErrorText: {
    alignSelf: "stretch",
    color: colors.black,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
    marginTop: 10,
    textAlign: "center",
  },
  loginNoticeText: {
    alignSelf: "stretch",
    color: "#dbeafe",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 10,
    textAlign: "center",
  },
  loginGoogleButton: {
    width: "100%",
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: "#1e293b",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 76,
    paddingHorizontal: 8,
    gap: 8,
    shadowColor: "#000000",
    shadowOpacity: 0.3,
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  loginGoogleButtonPressed: {
    opacity: 0.78,
  },
  loginAvatar: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: "#16478e",
    alignItems: "center",
    justifyContent: "center",
  },
  loginAvatarText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  loginGoogleText: {
    flex: 1,
    color: colors.white,
    fontSize: 13,
    fontWeight: "700",
  },
  loginGoogleMark: {
    width: 38,
    height: 38,
    borderRadius: 999,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  loginGoogleMarkImage: {
    width: 26,
    height: 26,
  },
  settingsRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.canvas,
    padding: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  settingsRowActive: {
    borderColor: colors.blue,
    backgroundColor: colors.navySurface,
  },
  settingsRowTitle: {
    color: colors.ink,
    fontWeight: "800",
  },
  settingsRowSubtitle: {
    color: colors.subtleText,
    fontSize: 12,
    marginTop: 2,
  },
  settingsRowValue: {
    color: colors.navyInk,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  settingsSubmenu: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.xs,
    gap: spacing.xs,
  },
  settingsSubmenuRow: {
    minHeight: 36,
    borderRadius: 8,
    paddingHorizontal: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  settingsSubmenuRowActive: {
    backgroundColor: colors.navySurface,
  },
  settingsSubmenuLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
    flex: 1,
  },
  settingsIconButton: {
    minWidth: 28,
    minHeight: 28,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsIconButtonLabel: {
    color: colors.navyInk,
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 20,
  },
});
