import type { useSubsystemBrowse } from "./robot/useSubsystemBrowse";
import type { useMaterialsBrowse } from "./inventory/useMaterialsBrowse";
import type { usePartsBrowse } from "./inventory/usePartsBrowse";
import type { usePurchaseBrowse } from "./inventory/usePurchaseBrowse";
import type { Dispatch, SetStateAction } from "react";
import type { StyleProp, TextStyle, ViewStyle } from "react-native";

import type { AppThemeColors } from "../theme";
import type { WorkLogDraftSyncStatus } from "../services/workLogDraftSync";
import type { Artifact, HelpRequest, Mechanism, Member, PartDefinition, PartInstance, Project, PurchaseItem, QaRequest, QaReport, ResponsibleGroup, RiskSeverity, Subsystem, Task, WorkLog, WorkType } from "../types/domain";
import type { MaterialRollup, SummaryChipData, ViewTab, WorkLogSortMode } from "../ui/types";
import type { AttendanceStatus } from "../types/status";
export type { AttendanceStatus } from "../types/status";

export type AttendanceRow = {
  member: Member;
  status: AttendanceStatus;
};

export type RiskRow = {
  detail: string;
  id: string;
  priority: RiskSeverity;
  source: string;
  subsystemId: string;
  title: string;
};

export type HomeActionItem = {
  detail: string;
  id: string;
  label: string;
  onPressTargetId: string;
  priority: "critical" | "high" | "medium";
  source: "purchase" | "task";
  title: string;
};

export type WorkLogListItem = WorkLog & {
  localDraftId?: string;
  syncError?: string;
  syncStatus?: WorkLogDraftSyncStatus;
};

type StateSetter<T> = Dispatch<SetStateAction<T>>;
type TextSetter = StateSetter<string>;
export type ResponsiveScreenStyles = {
  calloutBody: StyleProp<TextStyle>;
  calloutBox: StyleProp<ViewStyle>;
  calloutTitle: StyleProp<TextStyle>;
  editTag: StyleProp<TextStyle>;
  memberAvatar: StyleProp<ViewStyle>;
  memberRow: StyleProp<ViewStyle>;
  memberRowSelected: StyleProp<ViewStyle>;
  metaLine: StyleProp<TextStyle>;
  navCount: StyleProp<ViewStyle>;
  primaryAction: StyleProp<ViewStyle>;
  primaryActionLabel: StyleProp<TextStyle>;
  quickActionButton: StyleProp<ViewStyle>;
  quickActionButtonLabel: StyleProp<TextStyle>;
  rosterSection: StyleProp<ViewStyle>;
  rowBody: StyleProp<TextStyle>;
  rowCard: StyleProp<ViewStyle>;
  rowSubtitle: StyleProp<TextStyle>;
  rowTitle: StyleProp<TextStyle>;
  subsectionLabel: StyleProp<TextStyle>;
  tableHeaderText: StyleProp<TextStyle>;
};

export interface AppScreenProps {
  materialsBrowse: ReturnType<typeof useMaterialsBrowse>;
  subsystemBrowse: ReturnType<typeof useSubsystemBrowse>;
  partsBrowse: ReturnType<typeof usePartsBrowse>;
  purchaseBrowse: ReturnType<typeof usePurchaseBrowse>;
  appResponsiveStyles: ResponsiveScreenStyles;
  artifacts: Artifact[];
  projectsById: Record<string, Project>;
  attendancePreview: AttendanceRow[];
  attendanceSummary: SummaryChipData[];
  canMentorApprove: boolean;
  canSubmitQa: boolean;
  workTypesById: Record<string, WorkType>;
  editTagStyle: StyleProp<TextStyle>;
  filteredWorkLogs: WorkLogListItem[];
  helpRequests: HelpRequest[];
  homeActionItems: HomeActionItem[];
  homeTaskSummary: SummaryChipData[];
  isLandscapeCardLayout: boolean;
  isSyncing: boolean;
  mechanismsById: Record<string, Mechanism>;
  meetingAttendance: AttendanceRow[];
  members: Member[];
  membersById: Record<string, Member>;
  openCreateMemberEditor: (role?: Member["role"]) => void;
  openCreatePartDefinitionEditor: () => void;
  openCreatePurchaseEditor: () => void;
  openCreateQaReportEditor: (taskId?: string, qaRequestId?: string) => void;
  openCreateSubsystemEditor: () => void;
  openCreateWorkLogEditor: (taskId?: string) => void;
  openWorkLogFromTimer: () => void;
  approvePurchaseItem: (item: PurchaseItem, approved: boolean) => Promise<void>;
  createQaRequest: (subject: string, mentorId: string, taskId?: string | null) => void;
  openEditMemberEditor: (memberId: string) => void;
  openEditPartDefinitionEditor: (partDefinitionId: string) => void;
  updatePartInstance: (item: PartInstance, patch: Partial<Pick<PartInstance, "location" | "readinessStatus">>) => Promise<void>;
  openEditPurchaseEditor: (item: PurchaseItem) => void;
  openEditSubsystemEditor: (subsystem: Subsystem) => void;
  openEditTaskEditor: (task: Task) => void;
  openEditWorkLogEditor: (workLog: WorkLog) => void;
  openDuplicateTaskEditor: (task: Task) => void;
  openMaterialRestockEditor: (row: MaterialRollup) => void;
  openTaskQueueFromTask: (task: Task) => void;
  partDefinitionsById: Record<string, PartDefinition>;
  transitionPurchaseItem: (item: PurchaseItem, status: PurchaseItem["orderStatus"]) => Promise<void>;
  purchaseItems: PurchaseItem[];
  responsibleGroups: ResponsibleGroup[];
  qaRequests: QaRequest[];
  qaReports: QaReport[];
  riskRows: RiskRow[];
  riskSummary: SummaryChipData[];
  rosterAdmins: Member[];
  rosterExternal: Member[];
  rosterMentors: Member[];
  rosterStudents: Member[];
  selectedMemberId: string | null;
  setActiveTab: StateSetter<ViewTab>;
  setAttendanceStatusByMemberId: StateSetter<Record<string, AttendanceStatus>>;
  setSelectedMemberId: StateSetter<string | null>;
  setWorkLogSearch: TextSetter;
  setWorkLogSortMode: StateSetter<WorkLogSortMode>;
  setWorkLogSubsystemFilter: TextSetter;
  shiftTaskDueDates: (tasksToShift: Task[], dayDelta: number) => Promise<void>;
  subsystems: Subsystem[];
  subsystemsById: Record<string, Subsystem>;
  syncFromBackend: () => Promise<void>;
  taskById: Record<string, Task>;
  taskDependencies: import("../types/domain").TaskDependency[];
  tasks: Task[];
  themeColors: AppThemeColors;
  workLogSearch: string;
  workLogs: WorkLog[];
  workLogSortMode: WorkLogSortMode;
  workLogSubsystemFilter: string;
  workLogSummary: SummaryChipData[];
  workLogTimer: import("./worklogs/workLogTimer").WorkLogTimerState | null;
  workTimerIsActive: boolean;
  workTimerIsPaused: boolean;
  startWorkLogTimer: () => void;
  pauseWorkLogTimer: () => void;
}
