import { StyleSheet } from "react-native";

import {
  colors,
  loginColors,
  overlayColors,
  shadows,
} from "../../theme";

export const loginScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  screenLight: {
    backgroundColor: loginColors.lightShell,
  },
  screenDark: {
    backgroundColor: loginColors.darkShell,
  },
  safeArea: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    minHeight: 722,
    borderRadius: 29,
    alignItems: "center",
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 28,
  },
  cardLight: {
    backgroundColor: loginColors.lightCard,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.card,
  },
  cardDark: {
    backgroundColor: loginColors.darkShell,
  },
  badgeShadow: {
    shadowColor: overlayColors.darkShadow,
    shadowOpacity: 0.28,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 13 },
    elevation: 8,
  },
  logoImage: {
    width: 304,
    height: 334,
  },
  title: {
    color: colors.blue,
    fontSize: 28,
    fontWeight: "400",
    letterSpacing: 0,
    marginTop: 14,
    marginBottom: 16,
    textShadowColor: "rgba(0, 0, 0, 0.7)",
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 1,
  },
  emailRow: {
    width: "100%",
    minHeight: 50,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 18,
    paddingRight: 8,
  },
  emailRowLight: {
    backgroundColor: colors.blue,
    shadowColor: overlayColors.darkShadow,
    shadowOpacity: 0.23,
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  emailRowDark: {
    backgroundColor: loginColors.darkInput,
  },
  codeRow: {
    width: "100%",
    minHeight: 50,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 18,
    paddingRight: 8,
  },
  emailInput: {
    flex: 1,
    minWidth: 0,
    color: colors.white,
    fontSize: 13,
    paddingVertical: 12,
  },
  sendButton: {
    width: "100%",
    minHeight: 44,
    borderRadius: 999,
    backgroundColor: colors.red,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    paddingHorizontal: 16,
  },
  inlineSendButton: {
    width: "auto",
    flexShrink: 0,
    marginLeft: 8,
    marginTop: 0,
  },
  sendButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "700",
  },
  errorText: {
    alignSelf: "stretch",
    color: colors.black,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
    marginTop: 10,
    textAlign: "center",
  },
  noticeText: {
    alignSelf: "stretch",
    color: loginColors.notice,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 10,
    textAlign: "center",
  },
  devModeButton: {
    width: "100%",
    minHeight: 42,
    borderRadius: 999,
    backgroundColor: loginColors.devModeButton,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 76,
    paddingHorizontal: 8,
    gap: 8,
    shadowColor: overlayColors.darkShadow,
    shadowOpacity: 0.3,
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  devModeButtonPressed: {
    opacity: 0.78,
  },
  devModeAvatar: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: colors.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  devModeAvatarText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "800",
  },
  devModeText: {
    flex: 1,
    color: colors.white,
    fontSize: 13,
    fontWeight: "700",
  },
});
